//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApi123.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public int idRoles { get; set; }
        public decimal Salary { get; set; }
    
        internal virtual Roles Roles { get; set; }
    }
}
